version: '3'

volumes:
  chemister:

services:
  postgres:
    image: postgres:latest

    environment:
      POSTGRES_DB: chemister
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root

    volumes:
     - chemister:/var/lib/postgresql/data
     - ./ops/db-backups:/backup
    
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6378:6379"
    restart: always
